# Generated by Django 3.1.4 on 2020-12-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[(0, 'INACTIVE'), (1, 'ACTIVE')], default=1, max_length=120),
        ),
    ]
